title: Analogy-ANGLE Workshop
description: Co-located with IJCAI 2024. August 3rd or 4th, 2024 in Jeju, South Korea.
show_downloads: false
google_analytics: false
theme: jekyll-theme-dinky
github:
  is_user_page: false

