title: Analogy-ANGLE
description: IJCAI 2024 Workshop
show_downloads: false
google_analytics: false
theme: jekyll-theme-dinky
github:
  zip_url: http://example.com/download.zip
  another_url: another value
