title: Analogy-ANGLE
description: A new interdisciplinary workshop co-located with IJCAI 2024. Analogy-ANGLE will take place on August 4th, 2024 in Jeju, South Korea.
show_downloads: false
google_analytics: false
theme: jekyll-theme-dinky
github:
  is_user_page: false

