title: The First Workshop on Analogical Abstraction in Cognition, Perception, and Language (Analogy-ANGLE)
description: IJCAI 2024 Workshop
show_downloads: false
google_analytics: false
theme: jekyll-theme-dinky
