title: Analogy-ANGLE
description: IJCAI 2024 Workshop ![IJCAI 2024 Workshop](https://ijcai24.org/wp-content/uploads/2023/11/cropped-logo-1.png)
show_downloads: false
google_analytics: false
theme: jekyll-theme-dinky
github:
  is_user_page: false

